name: image_recovery
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

plugin:
  platforms:
    android:
      package: io.flutter.plugins.googlesignin
      pluginClass: GoogleSignInPlugin
    ios:
      pluginClass: FLTGoogleSignInPlugin
    web:
      default_package: google_sign_in_web
dependencies:
  google_sign_in_platform_interface: ^1.1.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
# The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  #animation listview, gridview...
  flutter_staggered_animations: ^0.1.2
  http: ^0.12.2
  # navigation
  sailor: ^0.7.1
  #design pattern bloc
  flutter_bloc: ^6.0.1
  #design pattern Service Locator
  get_it: ^4.0.4
  equatable: ^1.0.0
  #bottom sheet
  modal_bottom_sheet: ^0.2.0+1
  #image picker
  image_picker: ^0.6.7+14
  #camera
  camera: ^0.5.8+5
  path_provider: ^1.6.11
  photo_view: ^0.10.0
  #share preferences
  shared_preferences: ^0.5.8
  #circle checkbox
  circular_check_box: ^1.0.4
  # Interceptors, Global configuration, FormData, Request Cancellation, File downloading, Timeout
  dio: ^3.0.10
  #bottom navigation
  curved_navigation_bar: ^0.3.4
  fluttertoast: ^7.1.5
  extended_sliver: ^1.0.1
  extended_image: ^1.3.0
  # extended_image_library: 0.1.8
  image_editor: any
  #font
  google_fonts: ^1.1.1
  #icon
  flutter_icons: ^1.1.0
  #social
  share: ^0.6.5+4
  # save gallery
  gallery_saver: ^2.0.1
  # photo manager
  photo_manager: ^0.5.8
  #facebook login
  flutter_facebook_auth: ^1.0.0
  #google login
  firebase_core: ^0.5.0
  firebase_auth: ^0.18.0+1
  google_sign_in: ^4.5.3
  #compress image
  flutter_image_compress: ^0.7.0
  #open app settings
  app_settings: ^4.0.4
  #permission handle
  permission_handler: ^5.0.1+1
  #slide image
  carousel_slider: ^2.3.1
  #splash screen
  splashscreen: ^1.3.5
  sticky_headers: "^0.1.8"
  #check internet
  connectivity: ^2.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - images/
    - assets/locale/localization_en.json
    - assets/locale/localization_vi.json
    - images/dichvucong/

module:
  androidX: true